import Head from "next/head";
import Image from "next/image";
import HomeBanner from "../components/HomeBanner/HomeBanner";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className="container mx-auto">
        <HomeBanner />
      </main>
      <footer></footer>
    </div>
  );
}
